//! The report: a ledger of runs in, the markdown of `docs/bench.md` out.
//!
//! # Why markdown and why generated
//!
//! The output of a benchmark is an argument, and an argument lives in a
//! document a human reads, not in a terminal that scrolls away. So the
//! tool's job ends at a markdown table that is pasted into
//! `docs/bench.md` — reviewable in a diff, comparable against the last
//! run's paste, and readable on a machine that has nothing installed.
//!
//! Generated rather than hand-written because a hand-written table is a
//! table someone stopped updating in March. The header line names the
//! generator and the record count so a stale paste is visible at a
//! glance.
//!
//! # Why a missing number prints `?`
//!
//! Several columns come from the server's `stats` reply, and the server
//! is free to add and rename counters. `nitro-demo::control::i2p_line`
//! already settled the rule for that: report "the server's i2p figures as
//! a printable line, with the keys it is missing **named** rather than
//! silently zeroed". A `0` in a `paint µs` column is a claim that
//! painting was free; a `?` is the truth, which is that this build of the
//! server did not say. The distinction matters most in exactly the case
//! where it is tempting to skip — comparing two builds, one of which has
//! the counter.
//!
//! # Why the refresh pivot is its own table
//!
//! The question the pixel scenarios exist to answer is "where does the
//! path stop keeping up at 120 Hz that it kept up at 60". That is a
//! comparison between two rows which, in a per-scenario table sorted by
//! sweep point, are nowhere near each other. Putting them side by side
//! in a table of their own is the difference between the data being
//! present and the answer being visible.

use crate::record::Record;
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// The column header, and with it the column order.
///
/// `run` first because it is what a reader scans down; the two rate
/// columns next because they say whether the run was valid at all; then
/// the cost columns in the order the work happens (client mutations →
/// server paint → copy → wire bytes); `verdict` last because it is the
/// conclusion drawn from everything to its left.
///
/// `flip rise` sits next to the verdict because it is the evidence for
/// it. The server's `flip_interval_max_us` is a cumulative all-time
/// maximum, so its *value* says nothing about a given run and its **rise**
/// says everything — see [`Record::dropped`], where reading the value
/// alone once marked 25 of 45 clean runs as dropped. Printing the rise
/// lets a reader check the verdict rather than take it.
const HEADER: &str = "| run | presented/s | commits/s | mutations/frame | server µs/frame | client µs/frame | paint µs mean/max | copy µs mean | damage px | bytes/frame | flip rise µs | verdict |";

/// The markdown separator row matching [`HEADER`].
const SEPARATOR: &str = "|---|---|---|---|---|---|---|---|---|---|---|---|";

/// What to print for a server counter this run does not have.
///
/// See the module docs: a named gap, never a fabricated zero.
const MISSING: &str = "?";

/// How far below the refresh a run has to present before it is called
/// **slow** rather than merely imperfect: 15 %.
///
/// Well outside [`Record::kept_up`]'s 5 % tolerance, so a run is never
/// both "not keeping up" and "not slow enough to mention" by accident,
/// and far enough down that the cause has to be the client's own loop
/// rather than a couple of unlucky vblanks.
const SLOW_FRACTION: f64 = 0.85;

/// The whole report: a provenance line, one table per scenario family,
/// then the refresh pivot when there is anything to pivot.
///
/// Scenario tables come first because they are the data and the pivot is
/// a reading of it; a reader who disagrees with the pivot needs the rows
/// it was drawn from to already be above it.
#[must_use]
pub fn markdown(records: &[Record]) -> String {
    if records.is_empty() {
        // An empty report says so in one line. A header and an empty
        // table would look like a result — "we measured, and there was
        // nothing" — when the truth is that nothing was measured.
        return "<!-- generated by `nitro-bench report` -->\n\nNo runs in this ledger.\n"
            .to_owned();
    }
    let mut out = format!(
        "<!-- generated by `nitro-bench report`: {} run{} -->\n\n",
        records.len(),
        if records.len() == 1 { "" } else { "s" }
    );
    for (scenario, group) in group_by_scenario(records) {
        out.push_str(&table(&scenario, &group));
    }
    let pivot = refresh_pivot(records);
    if !pivot.is_empty() {
        out.push_str(&pivot);
    }
    out
}

/// One table: a `### title` heading, the header, and a row per record, in
/// the order the records arrived.
///
/// Arrival order and not a sort by any column: the ledger's order is the
/// order the sweep ran, which is monotonic in `n` or `size` by
/// construction, and re-sorting it by a *measured* column would let a
/// noisy run reorder the table and make two reports of the same data look
/// like different data.
#[must_use]
pub fn table(title: &str, records: &[Record]) -> String {
    let mut out = format!("### {title}\n\n{HEADER}\n{SEPARATOR}\n");
    for record in records {
        let _ = writeln!(
            out,
            "| {} | {:.1} | {:.1} | {:.1} | {:.1} | {:.1} | {} | {} | {} | {:.0} | {} | {} |",
            record.label(),
            record.presented_per_s(),
            record.commits_per_s(),
            record.mutations_per_frame(),
            record.server_cpu_us_per_frame(),
            record.client_cpu_us_per_frame(),
            paint_cell(record),
            stat_cell(record, "copy_us_mean", 1),
            stat_cell(record, "damage_px_mean", 0),
            record.bytes_per_frame(),
            record.flip_max_rise_us(),
            verdict(record),
        );
    }
    out.push('\n');
    out
}

/// The 60 Hz / 120 Hz comparison, or an empty string when no
/// `(scenario, n, size)` was run at two refresh rates.
///
/// Only the three columns that answer the question are carried over:
/// server cost per frame, the rate achieved, and the verdict. Everything
/// else is already in the scenario table above, and a wide pivot would
/// hide the one comparison it exists to make.
///
/// Rates are named by their rounded hertz rather than by millihertz, so
/// the columns read `60 Hz` and `120 Hz`; a mode that is really 59.94
/// therefore shares a column with a true 60, which is the grouping a
/// human means.
#[must_use]
pub fn refresh_pivot(records: &[Record]) -> String {
    // `BTreeMap` keyed by the sweep point, then by rate: deterministic
    // order without sorting floats, and the rate order falls out
    // ascending, which is the direction the question is asked in.
    let mut by_key: BTreeMap<(String, u64, u32), BTreeMap<u64, &Record>> = BTreeMap::new();
    let mut seen = Vec::new();
    for record in records {
        let key = (record.scenario.clone(), record.n, record.size);
        if !by_key.contains_key(&key) {
            seen.push(key.clone());
        }
        // Last run wins for a repeated (key, rate): a re-run is a
        // correction, not a second opinion.
        by_key
            .entry(key)
            .or_default()
            .insert(u64::from(record.refresh_mhz), record);
    }
    let pivots: Vec<_> = seen
        .into_iter()
        .filter_map(|key| {
            let rates = by_key.get(&key)?;
            (rates.len() >= 2).then_some((key, rates))
        })
        .collect();
    if pivots.is_empty() {
        return String::new();
    }
    let mut rates: Vec<u64> = pivots
        .iter()
        .flat_map(|(_, rates)| rates.keys().copied())
        .collect();
    rates.sort_unstable();
    rates.dedup();

    let mut out = String::from("### refresh pivot\n\n");
    out.push_str("| run |");
    for rate in &rates {
        let _ = write!(
            out,
            " {} Hz server µs/frame | {} Hz presented/s | {} Hz verdict |",
            hz(*rate),
            hz(*rate),
            hz(*rate)
        );
    }
    out.push('\n');
    out.push_str("|---|");
    for _ in &rates {
        out.push_str("---|---|---|");
    }
    out.push('\n');
    for ((scenario, n, size), by_rate) in pivots {
        let label = by_rate
            .values()
            .next()
            .map_or_else(|| format!("{scenario} n={n} size={size}"), |r| r.label());
        let _ = write!(out, "| {label} |");
        for rate in &rates {
            match by_rate.get(rate) {
                Some(record) => {
                    let _ = write!(
                        out,
                        " {:.1} | {:.1} | {} |",
                        record.server_cpu_us_per_frame(),
                        record.presented_per_s(),
                        verdict(record)
                    );
                }
                // A cell with no run is a gap in the sweep, and saying so
                // beats leaving the reader to infer it from a blank.
                None => {
                    let _ = write!(out, " {MISSING} | {MISSING} | {MISSING} |");
                }
            }
        }
        out.push('\n');
    }
    out.push('\n');
    out
}

/// Records grouped by scenario, families in order of first appearance.
///
/// First appearance rather than alphabetical: the ledger's order is the
/// order the suite ran, which groups the micro-benchmarks before the
/// effects because that is how the suite is written, and alphabetising
/// would interleave `boing-node` with `bitblt` for no reader's benefit.
fn group_by_scenario(records: &[Record]) -> Vec<(String, Vec<Record>)> {
    let mut order: Vec<String> = Vec::new();
    let mut groups: BTreeMap<String, Vec<Record>> = BTreeMap::new();
    for record in records {
        if !groups.contains_key(&record.scenario) {
            order.push(record.scenario.clone());
        }
        groups
            .entry(record.scenario.clone())
            .or_default()
            .push(record.clone());
    }
    order
        .into_iter()
        .filter_map(|name| groups.remove(&name).map(|group| (name, group)))
        .collect()
}

/// Millihertz as whole hertz, for a column heading.
fn hz(mhz: u64) -> u64 {
    // Round rather than truncate so 59 940 mHz reads as 60 Hz, which is
    // the mode a human would name it by.
    (mhz + 500) / 1_000
}

/// One `stats_after` counter, formatted, or [`MISSING`].
fn stat_cell(record: &Record, key: &str, decimals: usize) -> String {
    record.stat_after(key).map_or_else(
        || MISSING.to_owned(),
        |value| format!("{:.*}", decimals, value as f64),
    )
}

/// The `paint µs mean/max` cell: two counters in one column, each
/// independently present or `?`.
///
/// Both in one cell because the pair is the interesting thing — a mean of
/// 400 µs with a max of 20 000 is a completely different machine from a
/// mean of 400 with a max of 600 — and independently missing because a
/// server that reports one and not the other should still contribute the
/// one.
fn paint_cell(record: &Record) -> String {
    format!(
        "{}/{}",
        stat_cell(record, "paint_us_mean", 1),
        stat_cell(record, "paint_us_max", 1)
    )
}

/// The verdict cell: `ok`, `**dropped**` or `**slow**`.
///
/// The order of the tests is the order of blame. A flip gap is the
/// server's problem and is checked first, because a run that both dropped
/// frames and ran slow is a dropped-frame story. Only then does a rate
/// well under the refresh *without* a gap mean the client was the limit:
/// the server flipped on time every time, there was simply nothing new to
/// flip. Anything else that is not keeping up gets no bold — it is
/// within noise of the cap, and shouting about it would train the reader
/// to ignore the column.
fn verdict(record: &Record) -> &'static str {
    if record.dropped() {
        return "**dropped**";
    }
    if record.kept_up() {
        return "ok";
    }
    if record.presented_per_s() < SLOW_FRACTION * record.refresh_hz() {
        return "**slow**";
    }
    "ok"
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A run that keeps up at 60 Hz with every server counter present.
    fn healthy(scenario: &str, n: u64) -> Record {
        Record {
            scenario: scenario.to_owned(),
            n,
            width: 1_920,
            height: 1_080,
            refresh_mhz: 60_000,
            seconds: 10.0,
            commits: 600,
            presented: 600,
            frames_received: 600,
            mutations: 1_200,
            tx_bytes: 60_000,
            client_cpu_us: 600_000,
            server_cpu_us: 1_200_000,
            stats_after: [
                ("paint_us_mean".to_owned(), 420_u64),
                ("paint_us_max".to_owned(), 900),
                ("copy_us_mean".to_owned(), 130),
                ("damage_px_mean".to_owned(), 250_000),
                ("flip_interval_max_us".to_owned(), 16_700),
            ]
            .into_iter()
            .collect(),
            ..Record::default()
        }
    }

    #[test]
    fn a_table_has_a_header_and_a_row_per_record() {
        let records = [
            healthy("rects", 10),
            healthy("rects", 100),
            healthy("rects", 1_000),
        ];
        let out = table("rects", &records);
        let lines: Vec<&str> = out.lines().collect();
        assert_eq!(lines[0], "### rects");
        assert_eq!(lines[2], HEADER);
        assert_eq!(lines[3], SEPARATOR);
        let rows = lines.iter().filter(|l| l.starts_with("| rects")).count();
        assert_eq!(rows, 3);
        assert!(out.ends_with("\n\n"), "every table ends with a blank line");
        assert!(out.contains("| rects n=1000 |"), "{out}");
    }

    #[test]
    fn a_missing_stats_key_prints_a_question_mark_and_not_a_zero() {
        let mut record = healthy("plasma", 0);
        record.stats_after.remove("copy_us_mean");
        record.stats_after.remove("paint_us_max");
        let out = table("plasma", &[record]);
        let row = out.lines().find(|l| l.starts_with("| plasma")).unwrap();
        assert!(row.contains("420.0/?"), "{row}");
        assert!(row.contains("| ? |"), "{row}");
        assert!(
            !row.contains("| 0.0 | 250000 |"),
            "a gap must not read as zero: {row}"
        );
    }

    #[test]
    fn the_three_verdicts_each_fire() {
        let ok = healthy("rects", 10);
        assert_eq!(verdict(&ok), "ok");

        let mut dropped = healthy("rects", 10);
        dropped
            .stats_after
            .insert("flip_interval_max_us".to_owned(), 34_000);
        assert_eq!(verdict(&dropped), "**dropped**");

        // Half the rate with every flip on time: the client is the limit.
        let mut slow = healthy("rects", 10);
        slow.presented = 300;
        slow.commits = 300;
        assert_eq!(verdict(&slow), "**slow**");

        let out = table("rects", &[ok, dropped, slow]);
        assert!(out.contains("**dropped**") && out.contains("**slow**") && out.contains(" ok |"));
    }

    #[test]
    fn the_pivot_appears_only_with_two_refresh_rates_and_names_both() {
        let sixty = healthy("plasma", 0);
        assert!(refresh_pivot(std::slice::from_ref(&sixty)).is_empty());

        let mut fast = sixty.clone();
        fast.refresh_mhz = 120_000;
        fast.presented = 900;
        fast.commits = 900;
        let pivot = refresh_pivot(&[sixty.clone(), fast.clone()]);
        assert!(
            pivot.contains("60 Hz") && pivot.contains("120 Hz"),
            "{pivot}"
        );
        assert!(pivot.contains("### refresh pivot"), "{pivot}");
        let rows = pivot.lines().filter(|l| l.starts_with("| plasma")).count();
        assert_eq!(rows, 1, "{pivot}");
        assert!(pivot.ends_with("\n\n"), "{pivot}");

        // A different sweep point is a different key and does not pivot
        // against the first one.
        let mut other = fast.clone();
        other.n = 7;
        assert!(refresh_pivot(&[sixty, other]).is_empty());
    }

    #[test]
    fn a_pivot_gap_is_named_not_blank() {
        let a = healthy("rects", 1);
        let mut b = healthy("rects", 1);
        b.refresh_mhz = 120_000;
        let mut c = healthy("fire", 0);
        c.refresh_mhz = 144_000;
        let mut d = healthy("fire", 0);
        d.refresh_mhz = 60_000;
        let pivot = refresh_pivot(&[a, b, c, d]);
        assert!(pivot.contains("144 Hz"), "{pivot}");
        let rects = pivot.lines().find(|l| l.starts_with("| rects")).unwrap();
        assert!(rects.contains("| ? | ? | ? |"), "{rects}");
    }

    #[test]
    fn the_report_groups_by_scenario_in_first_appearance_order() {
        let records = [
            healthy("rects", 10),
            healthy("plasma", 0),
            healthy("rects", 100),
        ];
        let out = markdown(&records);
        assert!(out.starts_with("<!-- generated by `nitro-bench report`: 3 runs -->"));
        let rects = out.find("### rects").unwrap();
        let plasma = out.find("### plasma").unwrap();
        assert!(rects < plasma, "{out}");
        assert_eq!(out.matches("### rects").count(), 1);
    }

    #[test]
    fn an_empty_ledger_is_an_honest_sentence() {
        let out = markdown(&[]);
        assert!(out.contains("No runs"), "{out}");
        assert!(!out.contains(HEADER), "{out}");
    }

    #[test]
    fn a_single_run_is_not_pluralised() {
        let out = markdown(&[healthy("rects", 1)]);
        assert!(
            out.starts_with("<!-- generated by `nitro-bench report`: 1 run -->"),
            "{out}"
        );
    }

    #[test]
    fn millihertz_rounds_to_the_mode_a_human_names() {
        assert_eq!(hz(60_000), 60);
        assert_eq!(hz(59_940), 60);
        assert_eq!(hz(120_000), 120);
        assert_eq!(hz(0), 0);
    }
}
