//! Symbolic icons for the nitro desktop: a curated subset of
//! [Bootstrap Icons](https://github.com/twbs/icons) (MIT) baked into the
//! binary as SVG path data on a 16-unit grid, plus an anti-aliased coverage
//! rasteriser.
//!
//! # Why a crate and not a directory of files
//!
//! An icon is wanted at the moment a bar or a menu paints, on a machine that
//! may not have finished mounting anything. Shipping the paths *in* the binary
//! means there is no icon theme to look up, no `/usr/share` to stat, no
//! XDG-icon-spec cascade to walk, and no failure mode where the desktop starts
//! without pictures. The whole table is a few kilobytes of `&'static str`, so
//! it costs less than the code that would have loaded it from disk.
//!
//! # The handle is an index, not a name
//!
//! [`index_of`] resolves a name to a `u32` once, at the edge. Everything
//! downstream -- the scene graph, the cache key for a rasterised mask, the
//! wire protocol -- carries that `u32`. No string crosses into the scene
//! graph, so painting cannot allocate, hash, or compare a string, and an icon
//! reference is a machine word.
//!
//! The index is stable for a given build: [`ICONS`](set::ICONS) is sorted by
//! name, so the index only moves when the curated list itself changes and
//! `set.rs` is regenerated. It is *not* stable across such a regeneration and
//! must not be persisted or sent to a peer built from different source.
//!
//! # Rasterising
//!
//! [`rasterise`] renders an icon into a `px * px` [`Mask`] of 8-bit coverage.
//! Paths are authored on a [`GRID`]-unit box, so the transform is a uniform
//! `px / 16` scale and the result lands exactly inside the requested square --
//! an icon at 24 px and a glyph at 24 px occupy the same box and can be
//! composited without measuring either.
//!
//! Rasterising at the size actually wanted is the point. Scaling a 16 px mask
//! up to 32 px resamples four pixels of blur; rasterising at 32 px re-runs the
//! curves and produces real edges. The masks are small enough that this is
//! cheap: a 16 px mask is 256 bytes and a 48 px mask 2304, so an entire
//! desktop's worth of icons at every size it uses fits in a few tens of
//! kilobytes and never needs evicting.
//!
//! # Provenance
//!
//! `src/set.rs` is generated by `deploy/icons-import.sh` from a pinned
//! upstream commit and must not be edited by hand. The importer normalises
//! every path to absolute, arc-free commands, because zeno 0.3.3's SVG parser
//! mis-handles implicit repeated arc argument sets; the script documents this
//! in detail. The upstream MIT licence is carried in
//! `LICENSE.bootstrap-icons`.

mod set;

use set::ICONS;

/// The nominal grid the paths are authored on.
///
/// Every icon's geometry is inside `0.0..=16.0` on both axes, matching
/// Bootstrap's 16px viewBox. [`rasterise`] scales by `px / GRID`, so a caller
/// wanting an icon to line up with text at a given pixel size just asks for
/// that size.
pub const GRID: f32 = 16.0;

/// One symbolic icon: a name, one SVG path on a 16-unit grid, and its fill rule.
///
/// An icon's several upstream paths are concatenated into `path` at import
/// time. That is sound only because they share a fill rule -- the importer
/// rejects an icon whose paths disagree, since one flag cannot describe two
/// rules and filling both under either draws the wrong shape.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Icon {
    /// The upstream Bootstrap Icons name, e.g. `"volume-up"`.
    pub name: &'static str,
    /// SVG path data: absolute, arc-free, explicit command letters.
    pub path: &'static str,
    /// Fill with the even-odd rule rather than non-zero.
    ///
    /// Load-bearing, not cosmetic: the icons that set it are drawn as
    /// overlapping subpaths whose overlaps are meant to be holes.
    pub even_odd: bool,
}

/// Every icon, sorted by name.
///
/// The sort is what makes [`lookup`] a binary search and what fixes the
/// meaning of an index.
#[must_use]
pub fn all() -> &'static [Icon] {
    ICONS
}

/// The icon called `name`, by binary search.
///
/// Returns `None` for an unknown name rather than a placeholder: a missing
/// icon is a bug in the caller's name literal, and silently painting a
/// question mark would hide it until someone noticed the picture was wrong.
#[must_use]
pub fn lookup(name: &str) -> Option<&'static Icon> {
    index_of(name).and_then(at)
}

/// The index of `name` in [`all`] -- the stable handle the server uses as a
/// cache key and puts in the scene, so no string crosses into the scene graph.
///
/// Resolve once, at the edge; pass the `u32` everywhere after that.
#[must_use]
pub fn index_of(name: &str) -> Option<u32> {
    ICONS
        .binary_search_by_key(&name, |icon| icon.name)
        .ok()
        // The cast cannot truncate: the table is a curated list of a few dozen
        // entries, and `u32::MAX` icons would not fit in the binary.
        .map(|index| index as u32)
}

/// The icon at `index`, or `None`.
///
/// Out-of-range is `None` rather than a panic because an index may arrive from
/// a peer or a stale cache entry, and a display server must not abort over a
/// bad icon reference.
#[must_use]
pub fn at(index: u32) -> Option<&'static Icon> {
    ICONS.get(index as usize)
}

/// An 8-bit coverage mask: `w * h` bytes, tightly packed, one byte of alpha
/// per pixel.
///
/// Coverage, not colour. Symbolic icons are painted in the foreground colour
/// of whatever they sit in, so the rasteriser produces the shape and the
/// compositor supplies the tint -- the same A8 arrangement as the glyph atlas
/// in `nitro-text`, and for the same reason.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Mask {
    /// Width in pixels.
    pub w: u32,
    /// Height in pixels.
    pub h: u32,
    /// `w * h` bytes of alpha, row-major, no padding between rows.
    pub coverage: Vec<u8>,
}

impl Mask {
    /// The empty mask returned for a degenerate size.
    const EMPTY: Self = Self {
        w: 0,
        h: 0,
        coverage: Vec::new(),
    };
}

/// The largest icon anyone has a use for.
///
/// A bar icon is 16-24 px and a launcher tile 48-64; 512 is far past any of
/// that and exists only so that an arithmetic slip in a caller cannot ask for
/// a gigabyte of coverage.
const MAX_PX: u32 = 512;

/// Rasterise `icon` into a `px * px` anti-aliased coverage mask.
///
/// `px` is clamped to `1..=512`; `px == 0` yields an empty mask (`w == h == 0`)
/// rather than a panic, so a caller computing a size from a scale factor
/// cannot bring the server down by rounding to zero.
///
/// The mask is exactly `px` by `px`: the size is given explicitly rather than
/// derived from the path's bounding box, so the icon keeps its designed
/// padding inside the box and two different icons at the same size are
/// interchangeable. A caller that wants tight bounds should crop.
#[must_use]
pub fn rasterise(icon: &Icon, px: u32) -> Mask {
    if px == 0 {
        return Mask::EMPTY;
    }
    let px = px.min(MAX_PX);
    let scale = px as f32 / GRID;
    let mut coverage = vec![0u8; (px as usize) * (px as usize)];

    let style = if icon.even_odd {
        zeno::Fill::EvenOdd
    } else {
        zeno::Fill::NonZero
    };

    // `size` makes the placement explicit: with an explicit size zeno skips
    // bounds computation entirely and renders at the origin we asked for, so
    // the 16-unit box maps exactly onto the `px * px` box. `TopLeft` matches
    // the row-major, y-down convention of every other surface in the tree.
    zeno::Mask::new(icon.path)
        .style(style)
        .transform(Some(zeno::Transform::scale(scale, scale)))
        .origin(zeno::Origin::TopLeft)
        .size(px, px)
        .format(zeno::Format::Alpha)
        .render_into(&mut coverage, None);

    Mask {
        w: px,
        h: px,
        coverage,
    }
}

#[cfg(test)]
mod tests {
    use super::{Icon, Mask, all, at, index_of, lookup, rasterise};

    /// Pixels with partial coverage: the anti-aliased edge.
    fn edge_pixels(mask: &Mask) -> usize {
        mask.coverage
            .iter()
            .filter(|&&a| (1..=254).contains(&a))
            .count()
    }

    fn covered(mask: &Mask) -> usize {
        mask.coverage.iter().filter(|&&a| a != 0).count()
    }

    #[test]
    fn the_table_is_sorted_and_unique() {
        // Both halves of the contract the rest of the crate rests on: the sort
        // is what makes `lookup` a binary search, and uniqueness is what makes
        // an index mean one icon.
        let names: Vec<&str> = all().iter().map(|i| i.name).collect();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(
            names, sorted,
            "set.rs must be sorted by name with no duplicates"
        );
        assert!(!all().is_empty(), "the icon table is empty");
    }

    #[test]
    fn every_icon_rasterises_to_something() {
        // The test that catches a path zeno cannot parse. zeno does not report
        // a parse failure from `render_into` -- it renders whatever prefix it
        // understood -- so a mis-parsed path shows up as a mask that is empty
        // or far too sparse, never as an error. Checking every icon at two
        // sizes is the only way to notice.
        for icon in all() {
            assert_eq!(
                zeno::validate_svg(icon.path),
                Ok(()),
                "{}: zeno cannot parse the generated path",
                icon.name
            );
            for px in [16u32, 32] {
                let mask = rasterise(icon, px);
                assert_eq!(mask.w, px);
                assert_eq!(mask.h, px);
                assert!(
                    covered(&mask) > 0,
                    "{}: empty mask at {px} px -- path truncated or off-box",
                    icon.name
                );
            }
        }
    }

    #[test]
    fn coverage_is_exactly_the_declared_box() {
        // A mask whose buffer disagrees with its declared size is a buffer
        // overrun waiting to happen in the compositor, which indexes it as
        // `y * w + x` and trusts both numbers.
        for icon in all() {
            for px in [1u32, 16, 24, 48] {
                let mask = rasterise(icon, px);
                assert_eq!(
                    mask.coverage.len(),
                    (mask.w * mask.h) as usize,
                    "{}: coverage length disagrees with {}x{}",
                    icon.name,
                    mask.w,
                    mask.h
                );
            }
        }
    }

    #[test]
    fn no_ink_is_clipped_by_the_box() {
        // The claim `rasterise` makes is that the 16-unit box maps exactly
        // onto the `px * px` box. Asserting that icons stay *away* from the
        // border would be wrong -- most of this set is drawn edge to edge, and
        // a few (`search`, `gear`) have strokes whose outer half spills a
        // fraction of a unit past 0 or 16 by design. What must hold is that
        // none of that spill is actually *lost*: zeno clips silently, so a
        // transform that was off by a pixel would show up only as a shaved
        // edge that no one notices until the icon looks wrong.
        //
        // So render each icon into a deliberately padded box, translated by
        // the padding, and require the margin to be untouched. Any ink landing
        // there is ink the real `rasterise` call would have thrown away.
        const PX: u32 = 32;
        const PAD: u32 = 8;
        const SIDE: u32 = PX + 2 * PAD;

        for icon in all() {
            let style = if icon.even_odd {
                zeno::Fill::EvenOdd
            } else {
                zeno::Fill::NonZero
            };
            let scale = PX as f32 / super::GRID;
            let mut padded = vec![0u8; (SIDE as usize) * (SIDE as usize)];
            zeno::Mask::new(icon.path)
                .style(style)
                .transform(Some(
                    zeno::Transform::scale(scale, scale).then_translate(PAD as f32, PAD as f32),
                ))
                .origin(zeno::Origin::TopLeft)
                .size(SIDE, SIDE)
                .format(zeno::Format::Alpha)
                .render_into(&mut padded, None);

            let spilled: u32 = (0..SIDE)
                .flat_map(|y| (0..SIDE).map(move |x| (x, y)))
                .filter(|&(x, y)| !((PAD..PAD + PX).contains(&x) && (PAD..PAD + PX).contains(&y)))
                .map(|(x, y)| u32::from(padded[(y * SIDE + x) as usize]))
                .sum();
            assert_eq!(
                spilled, 0,
                "{}: ink falls outside the {PX}px box and would be clipped",
                icon.name
            );
        }
    }

    #[test]
    fn lookup_index_and_at_agree() {
        for (i, icon) in all().iter().enumerate() {
            let index = index_of(icon.name).expect("every table entry resolves");
            assert_eq!(
                index as usize, i,
                "{}: index_of disagrees with position",
                icon.name
            );
            assert_eq!(
                at(index),
                Some(icon),
                "{}: at() disagrees with the table",
                icon.name
            );
            assert_eq!(lookup(icon.name), Some(icon));
        }
    }

    #[test]
    fn unknown_names_and_indices_are_none() {
        // Names chosen to land before, inside and after the sorted table, so a
        // binary search that returned a neighbour instead of `None` is caught.
        for name in ["", "aaaaa", "definitely-not-an-icon", "zzzzz", "gear "] {
            assert_eq!(lookup(name), None, "{name:?} should not resolve");
            assert_eq!(index_of(name), None, "{name:?} should not resolve");
        }
        let past_end = u32::try_from(all().len()).expect("table fits in u32");
        assert_eq!(at(past_end), None);
        assert_eq!(at(u32::MAX), None);
    }

    #[test]
    fn zero_px_is_empty_and_huge_is_clamped() {
        let icon = lookup("square").expect("square is in the curated set");

        let empty = rasterise(icon, 0);
        assert_eq!((empty.w, empty.h), (0, 0));
        assert!(empty.coverage.is_empty());

        // Clamped, not honoured: a caller that computes 100_000 px from a bad
        // scale factor gets a large-but-survivable mask, not an OOM.
        let clamped = rasterise(icon, 100_000);
        assert_eq!((clamped.w, clamped.h), (super::MAX_PX, super::MAX_PX));
        assert_eq!(
            clamped.coverage.len(),
            (super::MAX_PX * super::MAX_PX) as usize
        );
    }

    #[test]
    fn the_fill_rule_reaches_the_rasteriser() {
        // That `even_odd` is actually wired to zeno's fill style, proved on a
        // shape built to tell the two rules apart: a square with a smaller
        // square inside it, both wound the same way. Non-zero counts two
        // positive crossings and fills the middle solid; even-odd counts two
        // crossings and leaves a hole.
        //
        // This is deliberately a synthetic path rather than a curated icon.
        // None of the 47 icons in the set renders differently under the two
        // rules -- their subpaths do not overlap, which is why upstream can be
        // careless about the attribute -- so no real icon can witness this.
        // See `even_odd_matches_upstream` for the other half: that the flag
        // still carries the *correct* value.
        let nested = "M0 0H16V16H0ZM4 4H12V12H4Z";
        let solid = rasterise(
            &Icon {
                name: "nested",
                path: nested,
                even_odd: false,
            },
            32,
        );
        let holed = rasterise(
            &Icon {
                name: "nested",
                path: nested,
                even_odd: true,
            },
            32,
        );

        assert_eq!(
            covered(&solid),
            32 * 32,
            "non-zero should fill the inner square"
        );
        assert!(
            covered(&holed) < covered(&solid),
            "even-odd should punch a hole the non-zero rule fills"
        );
        // The hole is the inner 8x8 units = 16x16 pixels at 32 px.
        assert_eq!(covered(&solid) - covered(&holed), 16 * 16);
    }

    #[test]
    fn even_odd_matches_upstream() {
        // The other half of the fill-rule contract: the importer must copy
        // `fill-rule="evenodd"` across faithfully. Because no curated icon
        // renders differently under the two rules, a dropped flag is
        // *invisible* today -- but it would become a wrong-looking icon the
        // moment someone adds an icon with overlapping subpaths, or upstream
        // redraws one of these. This ground truth is read off the pinned
        // Bootstrap sources, so it checks the importer against upstream rather
        // than against itself.
        const EVEN_ODD_UPSTREAM: &[&str] = &[
            "arrow-left",
            "arrow-up",
            "arrows-angle-expand",
            "chevron-right",
            "list",
            "plus-lg",
            "sliders",
        ];
        let actual: Vec<&str> = all()
            .iter()
            .filter(|i| i.even_odd)
            .map(|i| i.name)
            .collect();
        assert_eq!(
            actual, EVEN_ODD_UPSTREAM,
            "the set of evenodd icons drifted from the pinned upstream"
        );
    }

    #[test]
    fn thirty_two_px_is_re_rasterised_not_upscaled() {
        // The claim in the crate docs -- that asking for the size you want
        // beats scaling a small mask -- has to be true or the API is pointless.
        // A nearest-neighbour 2x of the 16 px mask has exactly the same set of
        // alpha values, each in a 2x2 block; a real 32 px rasterisation runs
        // the curves again and finds edge detail the 16 px grid could not
        // hold. Compare the anti-aliased edge: the true raster must have
        // strictly more partial-coverage pixels than the blow-up, which by
        // construction has exactly 4x the 16 px count.
        let icon = lookup("gear").expect("gear is in the curated set");
        let small = rasterise(icon, 16);
        let large = rasterise(icon, 32);

        let upscaled_edges = edge_pixels(&small) * 4;
        let real_edges = edge_pixels(&large);
        assert_ne!(
            real_edges, upscaled_edges,
            "32 px mask has the same edge budget as a 2x blow-up of the 16 px one"
        );

        // And the detail is genuinely new: a nearest-neighbour upscale repeats
        // each source pixel, so every 2x2 block is uniform. A real raster's
        // blocks are not.
        let varied = (0..16)
            .flat_map(|y| (0..16).map(move |x| (x, y)))
            .filter(|&(x, y)| {
                let at = |dx: usize, dy: usize| large.coverage[(y * 2 + dy) * 32 + x * 2 + dx];
                let first = at(0, 0);
                [at(1, 0), at(0, 1), at(1, 1)].iter().any(|&v| v != first)
            })
            .count();
        assert!(
            varied > 0,
            "every 2x2 block of the 32 px mask is uniform -- it looks like an upscale"
        );
    }

    #[test]
    fn a_solid_icon_fills_more_than_an_outline() {
        // Sanity that coverage means what it says, and that two different
        // entries really are different art rather than the same path imported
        // twice under two names.
        let filled = rasterise(lookup("circle-fill").expect("curated"), 32);
        let outline = rasterise(lookup("square").expect("curated"), 32);
        assert!(
            covered(&filled) > covered(&outline),
            "a filled disc should cover more than a square outline"
        );
        // A disc of radius 8 on a 16-unit grid fills pi/4 of its box.
        let ratio = covered(&filled) as f32 / (32.0 * 32.0);
        assert!(
            (0.7..=0.85).contains(&ratio),
            "circle-fill covers {ratio} of its box, expected about pi/4"
        );
    }
}
